# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Vertilux Ltd. Official Website
email: jose.perez@vertilux.com
description: >- # this means to ignore newlines until "baseurl:"
  Vertilux is one of the largest manufacturers and distributors of fabrics, components,
  and automated solutions for the Window Covering Industry.
  With more than 35 years of experience, Vertilux offers its clients the best fabrics and
  decorative & technical solutions, which ensure a successful business through excellent
  service and professional advice, oriented to the consumer.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://vertilux.com"

# Social Media
twitter: "https://twitter.com/vertilux"
facebook: "https://www.facebook.com/ideasforyourspace/"
youtube: "https://www.youtube.com/user/vertiluxcollection"
instagram: "https://www.instagram.com/vertilux_collection/"

# Sites
home:
  header: Vertilux Home
  url: "https://en.vertilux.com/"
  description: For those looking to buy Vertilux Blinds & Shades for your home or your clients, or want to learn more about the benefits of Vertilux Blind and Shades.
partner:
  header: Vertilux Partner
  url: "https://vertilux.com/en"
  description: For existing Vertilux Customers, Fabricators, or Dealers who are looking to buy fabrics, systems, automation and integrations solutions, or machinery.
spec:
  header: Vertilux Spec
  url: "http://specvertilux.com/"
  description: For architecs, developers, contractors, and builders who are working on a project that needs blinds and shades solutions, you can get professional spec resources on our Vertilux Spec portal.

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
